spring:
  jpa:
    show-sql: true
  resources:
    cache-period: 0

server:
  port: 8080
  compression:
    enabled: false

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.apache: INFO
    liquibase: INFO
    ch: INFO